### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by franklin-vidal** [tkashkin/ZLauncher#2]
I am a programmer but not C++ or C. I use the Code::Blocks to compile the source, and i get the error: 
`C:\Program Files (x86)\CodeBlocks\MinGW\lib\gcc\mingw32\4.9.2\include\c++\bits\locale_classes.h|344|error: '_Atomic_word' does not name a type`
What configuration i use to compile in Code::Blocks for generate the executable?

**Comment by tkashkin** [comment]
I'm using Code::Blocks v13.12 ![image](https://cloud.githubusercontent.com/assets/2003017/24581533/f6b3c0ce-1725-11e7-9268-7ad55e038338.png)
MinGW:
```
E:\IDE\CodeBlocks\MinGW\bin> .\g++.exe -v
Using built-in specs.
COLLECT_GCC=E:\IDE\CodeBlocks\MinGW\bin\g++.exe
COLLECT_LTO_WRAPPER=e:/ide/codeblocks/mingw/bin/../libexec/gcc/mingw32/4.7.1/lto-wrapper.exe
Target: mingw32
Configured with: ../../src/gcc-4.7.1/configure --build=mingw32 --enable-languages=c,c++,ada,fortran,objc,obj-c++ --enable-threads=win32 --enable-libgomp --enable-lto --enable-fully-dynamic-string --enable-libstdcxx-debug --enable-version-specific-runtime-libs --with-gnu-ld --disable-nls --disable-win32-registry --disable-symvers --disable-build-poststage1-with-cxx --disable-werror --prefix=/mingw32tdm --with-local-prefix=/mingw32tdm --enable-cxx-flags='-fno-function-sections -fno-data-sections' --with-pkgversion=tdm-1 --enable-sjlj-exceptions --with-bugurl=http://tdm-gcc.tdragon.net/bugs
Thread model: win32
gcc version 4.7.1 (tdm-1)
```
I will test with newer Code::Blocks and toolchain.

**Comment by tkashkin** [comment]
I've reproduced issue, trying to fix.

**Comment by tkashkin** [comment]
[Now](../commit/fbb1e7261af6c051171996f150e2b9088d196ee3) it should be compiled with any mingw build with **win32 thread model** e.g. [this](https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/6.3.0/threads-win32/dwarf/i686-6.3.0-release-win32-dwarf-rt_v5-rev2.7z/download).
