### ISSUE TITLE
a question and a suggestion

### ISSUE THREAD

**Issue by 7ack** [tkashkin/ZLauncher#3]
- Question
what the different between ' cutscenes playback using external mpv player' and the [cemuhook](https://sshnuke.net/cemuhook/) ? should i choose one or both?

- Suggestion
what about add some funtion to manage the Updates and DLC (NUSdownload and decrypt content  ) since CEMU 1.7.3 hassupported  Patch and DLC.

**Comment by tkashkin** [comment]
ZLauncher and Cemuhook works differently. Just choose what you like:
##### Cemuhook is hooking some Cemu functions and replacing its functionality.
###### Pros:
 * It's integrated into Cemu.
 * It works in another games, not BotW only.
 * It's more seamless integration: subtitles are visible, timings are correct.
###### Cons:
 * It interferes with Cemu, something can break after updates.
 * It's closed-source now.
---
##### ZLauncher is constantly reading Cemu log and shows cutscene in external borderless window.
###### Pros:
 * It doesn't touch Cemu in any way.
 * It most likely continue to work after updates.
###### Cons:
 * Video is shown in separate overlay.
 * Subtitles are hidden.
 * Timings may be broken.

**Comment by tkashkin** [comment]
For suggestion: I'm not sure why implement something that exists and works in another software. I used [MapleSeed](https://github.com/Tsume/Maple-Tree/releases/tag/slim) and it worked perfectly.

**Comment by 7ack** [comment]
got it ! thanks alot  i download the MapleSeed  and its nice!

**Comment by tkashkin** [comment]
Updated README.md with this info.
