### ISSUE TITLE
Current (v0.3) distribution is flagged as dangerous by Chrome

### ISSUE THREAD

**Issue by Ferdzz** [tkashkin/ZLauncher#5]
This warning pops up when downloading the file using google Chrome. If there is any way to figure out what exactly is identified as potentially malicous, it would be great to fix this. Might raise the popularity of this project.
![image](https://cloud.githubusercontent.com/assets/7923672/24840077/882f3042-1d34-11e7-8e87-36cc568657a2.png)
The learn more button links to [this](https://support.google.com/chrome/answer/6261569?visit_id=1-636273607792532107-3368750112&p=ib_download_blocked&hl=en&rd=1)

**Comment by tkashkin** [comment]
This warning is probably due to integrated speedhack. [Some antiviruses doesn't like Cheat Engine](https://virustotal.com/en/file/75399e802081a8897ebb365b61b7752093efd79e515067f18393021c61e520e0/analysis/).
Possible workaround is to exclude speedhack from release and provide it as separate download.
Another workaround is to not bundle speedhack at all and possibly [generate CE trainer at runtime](https://github.com/tkashkin/ZLauncher/issues/1#issuecomment-287661957) and use installed CE copy.

---

I'm also not sure if speedhack is still needed. Maybe just drop this feature?

**Comment by tkashkin** [comment]
UPD: For some reason archive without speedhack is flagged as dangerous too.

**Comment by Ferdzz** [comment]
I personally have no clue what Chrome detects as dangerous in the archive. Maybe something weird is going on inside of it? Or maybe it's corrupted. However that's unlikely since you just said that your new archive is flagged as dangerous too...

**Comment by tkashkin** [comment]
Virustotal is not detecting new archive so I don't know why Chrome still detects it. Maybe repacking in some other format will help. Maybe rar, 7z, sfx exe or custom installer will work.

**Comment by tkashkin** [comment]
Can you try to download [repackaged release](https://github.com/tkashkin/ZLauncher/releases/tag/v0.3_installer)? Also can you recheck regular v0.3 archives because now for some reason chrome downloads it without blocking.

**Comment by Ferdzz** [comment]
Just tried it, the speedhack-free archive as well as the setup still raise a flag when downloading on Chrome

**Comment by tkashkin** [comment]
I've correctly downloaded all archives and installer with chrome 10 hours ago but now only speedhack-free archive works.
![chrome](https://cloud.githubusercontent.com/assets/2003017/24860500/90fd36fa-1dfd-11e7-8dab-e6831599cbdf.png)

**Comment by jonbarrow** [comment]
Just to put in my two-cents (even though this is slightly old) :
Have you tried double-packaging the file? Back when I used to make cracks for software, many sites would flag the cracks, but double-packaging them ( a rar/zip inside a rar/zip ) would get around this. Doing something similar might fix Chrome flagging the download here.

**Comment by tkashkin** [comment]
Try [updated installer](https://github.com/tkashkin/ZLauncher/releases/download/v0.3_installer/ZLauncher_setup.exe). It should download mpv and speedhack if checkboxes are set.

**Comment by Ferdzz** [comment]
Seems like Chrome is okay with the installer. Good job fixing this 👍
