### ISSUE TITLE
Videos not running

### ISSUE THREAD

**Issue by amunozj** [tkashkin/ZLauncher#8]
Hi I just reached the first tower, and I think I should have seen the cutscene, but it was all messed up I don't know if I'm doing things correctly.   This is my .ini

[cemu]
path=C:\WiiU\cemu175_066f500d8bce488
fullscreen=true
cores=0,2,4,6
cmdline=

[game]
path=C:\WiiU\BoTW\BoTW
elevate=false

[speedhack]
path=.\speedhack.exe
enabled=true

[video]
enabled=true

[steam]
enabled=false
elevate=true
gameid=12927812811798609920

If I set Elevate to true, the game doesn't work.    I activated logging as per the instructions.   Thanks for any help you may provide.

Please keep up the good work!

Andrés

**Comment by tkashkin** [comment]
In some cases ZLauncher can't read Cemu log if it's not running with elevated priveleges.
What exactly happens if set `[game].elevate=true`?

Try to get error code by running `start /wait zlauncher.exe && echo %errorlevel%` using cmd

This are the possible error codes:
```cpp
#define ERR_SUCCESS             0    // everything ok
#define ERR_CONFIG              1    // config is not found or paths in config are empty
#define ERR_ELEVATION           2    // user cancelled UAC elevation request
#define ERR_GAME                3    // error when starting Cemu
#define ERR_SPEEDHACK           4    // error when starting speedhack
#define ERR_STEAM_ELEVATION     5    // user cancelled UAC elevation request for Steam
#define ERR_STEAM_GAME          6    // error when starting Cemu through Steam
```

**Comment by amunozj** [comment]
thank you so much for your answer!   When I set:

[game]
path=C:\WiiU\BoTW\BoTW
elevate=true

and run start /wait zlauncher.exe && echo %errorlevel% using cmd

I see a terminal window for a second, windows asks me if I want to elevate ZLauncher, I say yes and the process ends.   This throws an error code of 0


 When I set:

 [game]
path=C:\WiiU\BoTW\BoTW
elevate=false

and run start /wait zlauncher.exe && echo %errorlevel% using cmd

I see a terminal window for a second, windows asks me if I want to elevate ZLauncher, I say yes and the game starts.   This also throws an error code of 0

Both throw an error code of 0, but in one case it doesn't work.  It seems to be my bitdefender antivirus. It reported finding a Rootkit.78958 virus in speedhack.exe

If I set the init file to:

[game]
path=C:\WiiU\BoTW\BoTW
elevate=true

[speedhack]
path=.\speedhack.exe
enabled=false

it works.  would you suggest changing speedhack for cheatengine?

**Comment by tkashkin** [comment]
You can disable and remove speedhack if you don't need it or add it to your antivirus whitelist.

**Comment by amunozj** [comment]
It works! thank you Tkashkin! it turns out I didn't needed speehack the game runs fine without it! thank you so much for putting this together.  God bless you!
